version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@dev:24

mvn-build-test-command: &mvn-build-test-command
  mvn-build-test-command: mvn verify -Dlicense.skip=true -Dmaven.javadoc.skip=true

mvn-collect-artifacts-command: &mvn-collect-artifacts-command
  mvn-collect-artifacts-command: |
    mkdir -p artifacts/cli artifacts/coverage artifacts/junit artifacts/javadoc
    cp **/target/*.jar artifacts/
    cp modules/cli-module/target/*standalone* artifacts/cli/
    cp -a target/apidocs/. artifacts/javadoc/
    cp -a modules/jacoco-aggregator-module/target/site/jacoco-aggregate/. artifacts/coverage/
    cp -a **/target/surefire-reports/. artifacts/junit

mvn-deploy-command: &mvn-deploy-command
  mvn-deploy-command: mvn -s .circleci/maven-release-settings.xml clean deploy -DdeployAtEnd=true -DperformRelease=true -DskipTests -Dspotbugs.skip=true -Djacoco.skip=true
  context: RELEASE_PROFILE_BBOTTEMA

workflows:
  workflow:
    jobs:
      - github-maven-deploy/build-and-test:
          <<: *mvn-build-test-command
          <<: *mvn-collect-artifacts-command
          filters:
            branches:
              only: develop

      - github-maven-deploy/approve-deploy-patch-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-minor-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-major-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test
      - github-maven-deploy/approve-deploy-as-is-version:
          type: approval
          requires:
            - github-maven-deploy/build-and-test

      - github-maven-deploy/deploy-patch-version:
          requires:
            - github-maven-deploy/approve-deploy-patch-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-minor-version:
          requires:
            - github-maven-deploy/approve-deploy-minor-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-major-version:
          requires:
            - github-maven-deploy/approve-deploy-major-version
          <<: *mvn-deploy-command
      - github-maven-deploy/deploy-as-is-version:
          requires:
            - github-maven-deploy/approve-deploy-as-is-version
          <<: *mvn-deploy-command
